version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: vj_postgres
    restart: always
    environment:
      POSTGRES_DB: vj_shopping_world
      POSTGRES_USER: vj_admin
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0
    container_name: vj_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: vj_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data:
