version: "1"
services:
  - type: web
    name: vj-shopping-world-backend
    runtime: node
    repo: https://github.com/vishaljatav777/VJ-Shopping-World
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: "5000"
      - key: NODE_ENV
        value: "production"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
