services:
  - type: web
    name: vj-express-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: vj-postgres-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: vj-postgres-db
    databaseName: vj_shopping_world
    user: vj_user

